[package]
name = "lzw_arc"
version = "0.1.0"
authors = ["AlukardBF <alukard.develop@gmail.com>"]
edition = "2018"

[dependencies]
bitvec = "0.10"
tiny-aes-rs = { git = "https://github.com/AlukardBF/tiny_aes_rs" }

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "archive_bench"
harness = false